# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:    
    docker:    
      # The primary container is an instance of the first image listed. The job's commands run in this container.
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo/api
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: ls
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      # run tests!
      - run: mvn install -Dmaven.test.skip=true'
      - run: mvn clean package -DskipTests=true'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: demo6