# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
    working_directory: ~/maven
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    branches:
      only:
        - demo6

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies    
      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }} 
            # - v1-dependencies-{{ checksum "pom.xml" }}
            # # fallback to using the latest cache if no exact match is found
            # - v1-dependencies-
            
      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
         # key: v1-dependencies-{{ checksum "pom.xml" }}
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      # run tests!
      - run: mvn integration-test