# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  api:
    docker:    
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk    
    working_directory: ~/repo 
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m


    # branches:
    #   only:
    #     - demo6
    steps:
      - checkout
      - save_cache:
          paths:
            - ~/.m2
         # key: v1-dependencies-{{ checksum "pom.xml" }}
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      # run tests!
      - run: cd api && mvn install -Dmaven.test.skip=true'
      - run: cd api && mvn clean package -DskipTests=true'
